package models;

/**
 * This is an abstract class used by classes which implement the {@code ID} property
 * 
 * <p> Implementing this abstract class will allow others to identify objects of a class using their {@code ID}
 * 
 * <p> It is recommended to generate the {@code ID} property randomly.
 * This generation is implemented differently in each class, however a good method would be
 * to generate this value based on the object's class name and it's other properties
 * 
 * <p> <i>Created on 14/05/2023 by Muhammad Putra</i>
 * 
 * @author		Muhammad Putra
 * @version		1.3
 * @since		1.0
 */
public abstract class Identifiable {


	
/* --------------------------- Private Attributes --------------------------- */
//region

	protected String id;

//endregion



/* --------------------------- Getters and Setters -------------------------- */
//region

	/** 
	 * Returns the autogenerated ID for this object
	 * 
	 * @return String		- the object's id
	 */
	public String getId() {
		return id;
	}

//endregion



/* ----------------------------- Utility Methods ---------------------------- */
//region

	/** 
	 * Returns this object as a string representation
	 * 
	 * <p> This method formats the properties in the following way:
	 * <p> {@code ID: <id>}
	 */	
	@Override
	public String toString() {
		return String.format("ID: %s", this.id);
	}

	/** 
	 * This is an abstract method which should be called to generate the ID for this object
	 */	
	public abstract void generateId();

//endregion



}
